# Implementation of Logistic Regression

In [1]:
import numpy as np
import seaborn as sns
from sklearn.datasets import make_classification

In [2]:
x, y = make_classification()

In [3]:
x

array([[ 0.35657103, -0.22609559,  0.1446475 , ...,  0.55378642,
         0.5224974 , -0.29684024],
       [-0.18003479, -0.72429658, -0.04744767, ...,  0.22108747,
        -0.28431463,  1.50972392],
       [-0.58253662, -0.12964548, -0.23333861, ...,  0.44718454,
        -1.17878113, -1.20259186],
       ...,
       [ 0.14217404,  0.4033029 ,  0.69784039, ...,  0.30700112,
        -0.66706916,  0.28271509],
       [ 0.4112029 , -0.39116345,  0.14720305, ..., -0.33402724,
         0.1413599 ,  0.14369687],
       [ 0.08859674, -0.70214273,  0.58472255, ..., -0.46007944,
         0.78662253, -0.95620304]])

In [4]:
y

array([0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1])

In [5]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([2, 3, 4, 5])

In [7]:
np.cross([arr1, arr2])

TypeError: cross() missing 1 required positional argument: 'b'

In [8]:
arr1.dot(arr2)

np.int64(40)

In [9]:
arr1 * arr2

array([ 2,  6, 12, 20])