<a href="https://colab.research.google.com/github/adnaen/machine-learning-notes/blob/main/DEEP_LEARNING/logistics_regression_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Logistic Regression Using PyTorch**

In [1]:
import torch
from torch import nn
from torch import Tensor

In [2]:
# device = "cuda" if torch.cuda.is_available() else "cpu"
# torch.set_default_device(device=device)

In [17]:
from sklearn.model_selection import train_test_split

torch.random.manual_seed(34)

# Dummy Data
x = torch.randn(500,10)
y = torch.randint(0, 2, (500, 1)).float()

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.2, shuffle=True, random_state=38947)

print("Shape of data")
(x_train.shape, y_train.shape), (x_test.shape, y_test.shape)

Shape of data


((torch.Size([400, 10]), torch.Size([400, 1])),
 (torch.Size([100, 10]), torch.Size([100, 1])))

In [18]:
class LogisticRegression(nn.Module):

    def __init__(self, ip_features: int, op_features: int) -> None:
        super().__init__()
        self.ip_features = ip_features
        self.op_features = op_features

        self.layer = nn.Linear(self.ip_features, self.op_features)
        self.activation = nn.Sigmoid()

    def forward(self, x: Tensor) -> Tensor:
        z = self.layer(x)
        a = self.activation(z)
        return a

In [22]:
print(y[:10])

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.]])


In [27]:
model = LogisticRegression(10, 1)

# training
epochs: int = 500
criterion = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters())

for i in range(epochs):
    y_pred = model(x_train)
    loss = criterion(y_pred, y_train)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if i % 100 == 0:
        print(f"Epoch : {i}, Loss: {loss.item()}")

Epoch : 0, Loss: 0.7407676577568054
Epoch : 100, Loss: 0.7060562372207642
Epoch : 200, Loss: 0.6901274919509888
Epoch : 300, Loss: 0.6834936738014221
Epoch : 400, Loss: 0.6808829307556152


In [34]:
y_test_prob = model(x_test)
bool_result = (y_test_prob >= .5).int()
bool_result.T

tensor([[0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
         1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
         0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
         1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
         0, 0, 0, 0]], dtype=torch.int32)

In [39]:
y_test.int().T

tensor([[1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
         1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
         1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
         1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 0, 1, 1]], dtype=torch.int32)