<a href="https://colab.research.google.com/github/adnaen/machine-learning-notes/blob/main/DEEP_LEARNING/pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PyTorch Tutorial To Get Started**

In [74]:
import torch

In [75]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

**Tensors**
```
scaler = single value
vector = 1-Dim tensor
matrix = 2-Dim tensor
tensor = N-Dim tensor
```

create random (3,4) `tensor` and print its shape

In [76]:
random_tensor = torch.rand((3,4), device=device)
print(f"Random Tensor: {random_tensor}")
print(f"Tensor size: {random_tensor.shape}")
print(f"Tensor Dimension : {random_tensor.ndim}")

Random Tensor: tensor([[0.5583, 0.0985, 0.7192, 0.9854],
        [0.8710, 0.2661, 0.8546, 0.5825],
        [0.1877, 0.2421, 0.9709, 0.6170]], device='cuda:0')
Tensor size: torch.Size([3, 4])
Tensor Dimension : 2


create tensor with `ones` with shape (2,5), and convert it to Numpy Array

In [77]:
ones_tensor = torch.ones((2,5), device=device)
ones_tensor.cpu().numpy()

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

perform `element wise addition` of two tensors of shape (4,4)

In [78]:
a = torch.rand(4,4, device=device)
b = torch.rand(4,4, device=device)
print(f"A : {a}")
print(f"B : {b}")

sum_of_ab = a + b
mul_of_ab = a * b

print(f"Sum of A and B : {sum_of_ab}")
print(f"Multiply A with B : {mul_of_ab}")

A : tensor([[0.2371, 0.4362, 0.9468, 0.6972],
        [0.0722, 0.1591, 0.6380, 0.6694],
        [0.7067, 0.8732, 0.6035, 0.3289],
        [0.4799, 0.9004, 0.7413, 0.7889]], device='cuda:0')
B : tensor([[0.6116, 0.4010, 0.2082, 0.9436],
        [0.8716, 0.5758, 0.3271, 0.1345],
        [0.9979, 0.7957, 0.9497, 0.1168],
        [0.2380, 0.0022, 0.2344, 0.4519]], device='cuda:0')
Sum of A and B : tensor([[0.8486, 0.8372, 1.1550, 1.6408],
        [0.9438, 0.7350, 0.9652, 0.8040],
        [1.7046, 1.6690, 1.5532, 0.4458],
        [0.7179, 0.9026, 0.9758, 1.2409]], device='cuda:0')
Multiply A with B : tensor([[0.1450, 0.1749, 0.1971, 0.6579],
        [0.0629, 0.0916, 0.2087, 0.0901],
        [0.7052, 0.6949, 0.5731, 0.0384],
        [0.1142, 0.0020, 0.1738, 0.3566]], device='cuda:0')


create a tensor with values [2,6,8] and `reshape` it into a (2,2)

In [79]:
new_tensor = torch.tensor([2, 4, 6, 8])
new_tensor.reshape([-1,2])

tensor([[2, 4],
        [6, 8]])

`generate a tensor` of random integers between 0 and 10 wih shape (3,3)

In [80]:
torch.randint(low=0, high=10, size=(3,3), device=device)

tensor([[1, 2, 6],
        [3, 8, 1],
        [9, 6, 2]], device='cuda:0')

### **AutoGrad**
- autograd automatically computes gradients for tensors involved in computation.
- It tracks all operations on tensors that have requires_grad=True and builds a computational graph dynamically.
- This enables backpropagation, where gradients are computed and stored for optimization.

In [81]:
# define a autograd enabled tensor
x = torch.tensor(2., requires_grad=True)
y = torch.tensor(5., requires_grad=True)

print(f"x : {x}")
print(f"y : {y}")

x : 2.0
y : 5.0


In [86]:
result = x**2 + y**2
print(f"Result : {result}")

Result : 29.0


In [87]:
# backpropgation
result.backward()

In [88]:
#find gradient
x.grad

tensor(5.)

In [89]:
y.grad

tensor(11.)

In [90]:
# reset a autograd
x.grad.zero_()

tensor(0.)

In [91]:
y.grad.zero_()

tensor(0.)

In [92]:
# run without autograd for temporary
with torch.no_grad():
    y = x*2 # not tracked

In [93]:
# detach autograd
z = y.detach()

In [95]:
# check if a tensor enabled autograd by
print(y.requires_grad)
print(x.requires_grad)

False
True
