<a href="https://colab.research.google.com/github/adnaen/machine-learning-notes/blob/main/DEEP_LEARNING/pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [13]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

create random (3,4) `tensor` and print its shape

In [23]:
tensor = torch.rand((3,4))
print(tensor.size())

torch.Size([3, 4])


create tensor with `ones` with shape (2,5), and convert it to Numpy Array

In [5]:
ones_tensor = torch.ones((2,5))
ones_tensor.numpy()

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

perform `element wise addition` of two tensors of shape (4,4)

In [7]:
a = torch.rand(4,4)
b = torch.rand(4,4)

a*b

tensor([[0.0857, 0.1249, 0.0331, 0.6429],
        [0.0771, 0.1771, 0.1775, 0.6819],
        [0.0142, 0.6532, 0.0247, 0.8613],
        [0.4183, 0.0138, 0.8042, 0.9174]])

create a tensor with values [2,6,8] and `reshape` it into a (2,2)

In [11]:
new_tensor = torch.tensor([2, 4, 6, 8])
new_tensor.reshape([2,2])

tensor([[2, 4],
        [6, 8]])

`generate a tensor` of random integers between 0 and 10 wih shape (3,3)

In [24]:
torch.randint(low=0, high=10, size=(3,3))

tensor([[0, 4, 5],
        [2, 4, 2],
        [4, 3, 4]])