<a href="https://colab.research.google.com/github/adnaen/machine-learning-notes/blob/main/deep_learning/5_rnn/rnn_training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:
import torch

In [47]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [74]:
VOCCAB = {"hello": 0, "dog": 1, "cat": 2, "tiger": 3, "lion": 4}
corpus = (
    [['hello'],['dog']],
    [['hello'], ['cat']],
    [['hello'], ['tiger']],
    [['hello'], ['lion']],
)

In [75]:
corpus

([['hello'], ['dog']],
 [['hello'], ['cat']],
 [['hello'], ['tiger']],
 [['hello'], ['lion']])

In [95]:
corpus_indexed = []
for sentence in corpus:
    corpus_indexed.append(torch.tensor([VOCCAB[token[0]] for token in sentence]))

print(corpus_indexed)

[tensor([0, 1]), tensor([0, 2]), tensor([0, 3]), tensor([0, 4])]


In [119]:
embeddings = torch.nn.Embedding(num_embeddings=5, embedding_dim=3)

In [120]:
embeddings(corpus_indexed[0])

tensor([[ 0.9844, -0.8460, -0.0011],
        [-0.1350,  0.2500, -0.6853]], grad_fn=<EmbeddingBackward0>)

In [146]:
embeddings(corpus_indexed[2])

tensor([[ 0.9844, -0.8460, -0.0011],
        [ 0.5976, -0.0316,  0.0848]], grad_fn=<EmbeddingBackward0>)

In [128]:
rnn = torch.nn.RNN(input_size=3, hidden_size=4)

In [129]:
op, hd = rnn(embeddings(corpus_indexed[1]))
op, hd

(tensor([[ 0.6573,  0.2925, -0.3636, -0.2539],
         [-0.0030,  0.3424, -0.5733,  0.3162]], grad_fn=<SqueezeBackward1>),
 tensor([[-0.0030,  0.3424, -0.5733,  0.3162]], grad_fn=<SqueezeBackward1>))

In [136]:
rnn.parameters

<bound method Module.parameters of RNN(3, 4)>

In [133]:
linear = torch.nn.Linear(4, 1)
linear(hd)

tensor([[0.4041]], grad_fn=<AddmmBackward0>)

In [45]:
x_ = torch.randint(0, 6, (1,6), device=device)
x_

tensor([[0, 1, 2, 0, 3, 1]], device='cuda:0')

In [22]:
y_ = torch.randint(0, 2, (1, 6), device=device)