<a href="https://colab.research.google.com/github/adnaen/machine-learning-notes/blob/main/deep_learning/0_pytorch/pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PyTorch Tutorial To Get Started**

In [1]:
import torch

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

**Tensors**
```
scaler = single value
vector = 1-Dim tensor
matrix = 2-Dim tensor
tensor = N-Dim tensor
```

create random (3,4) `tensor` and print its shape

In [3]:
random_tensor = torch.rand((3,4), device=device)
print(f"Random Tensor: {random_tensor}")
print(f"Tensor size: {random_tensor.shape}")
print(f"Tensor Dimension : {random_tensor.ndim}")

Random Tensor: tensor([[0.0908, 0.7569, 0.7842, 0.8760],
        [0.0895, 0.4326, 0.2259, 0.3905],
        [0.9944, 0.0490, 0.2349, 0.1837]], device='cuda:0')
Tensor size: torch.Size([3, 4])
Tensor Dimension : 2


create tensor with `ones` with shape (2,5), and convert it to Numpy Array

In [4]:
ones_tensor = torch.ones((2,5), device=device)
ones_tensor.cpu().numpy()

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

perform `element wise addition` of two tensors of shape (4,4)

In [5]:
a = torch.rand(4,4, device=device)
b = torch.rand(4,4, device=device)
print(f"A : {a}")
print(f"B : {b}")

sum_of_ab = a + b
mul_of_ab = a * b

print(f"Sum of A and B : {sum_of_ab}")
print(f"Multiply A with B : {mul_of_ab}")

A : tensor([[0.6856, 0.6964, 0.5898, 0.8699],
        [0.9283, 0.1532, 0.4939, 0.9284],
        [0.0513, 0.4674, 0.9029, 0.9379],
        [0.4604, 0.7335, 0.6692, 0.2781]], device='cuda:0')
B : tensor([[0.8028, 0.0624, 0.2449, 0.3780],
        [0.3192, 0.4132, 0.3336, 0.2171],
        [0.3328, 0.5272, 0.2627, 0.9491],
        [0.5578, 0.9529, 0.6102, 0.8856]], device='cuda:0')
Sum of A and B : tensor([[1.4884, 0.7588, 0.8347, 1.2479],
        [1.2474, 0.5663, 0.8275, 1.1455],
        [0.3841, 0.9947, 1.1656, 1.8869],
        [1.0182, 1.6865, 1.2795, 1.1637]], device='cuda:0')
Multiply A with B : tensor([[0.5504, 0.0435, 0.1444, 0.3288],
        [0.2963, 0.0633, 0.1648, 0.2015],
        [0.0171, 0.2464, 0.2372, 0.8901],
        [0.2568, 0.6990, 0.4084, 0.2463]], device='cuda:0')


create a tensor with values [2,6,8] and `reshape` it into a (2,2)

In [6]:
new_tensor = torch.tensor([2, 4, 6, 8])
new_tensor.reshape([-1,2])

tensor([[2, 4],
        [6, 8]])

`generate a tensor` of random integers between 0 and 10 wih shape (3,3)

In [7]:
torch.randint(low=0, high=10, size=(3,3), device=device)

tensor([[4, 0, 9],
        [0, 7, 0],
        [6, 7, 1]], device='cuda:0')

### **AutoGrad**
- autograd automatically computes gradients for tensors involved in computation.
- It tracks all operations on tensors that have requires_grad=True and builds a computational graph dynamically.
- This enables backpropagation, where gradients are computed and stored for optimization.

In [8]:
# define a autograd enabled tensor
x = torch.tensor(2., requires_grad=True)
y = torch.tensor(5., requires_grad=True)

print(f"x : {x}")
print(f"y : {y}")

x : 2.0
y : 5.0


In [9]:
result = x**2 + y**2
print(f"Result : {result}")

Result : 29.0


In [10]:
# backpropgation
result.backward()

In [11]:
#find gradient
x.grad

tensor(4.)

In [12]:
y.grad

tensor(10.)

In [13]:
# reset a autograd
x.grad.zero_()

tensor(0.)

In [14]:
y.grad.zero_()

tensor(0.)

In [15]:
# run without autograd for temporary
with torch.no_grad():
    y = x*2 # not tracked

In [16]:
# detach autograd
z = y.detach()

In [17]:
# check if a tensor enabled autograd by
print(y.requires_grad)
print(x.requires_grad)

False
True


## **Dataset, DataLoader, Batch Traning**

- Implement Abstract Dataset class, with `__len__`, `__getitem__` methods.

In [18]:
from torch.utils.data import Dataset, DataLoader

In [19]:
class CustomeAgeDataset(Dataset):
    def __init__(self, x: torch.Tensor, y: torch.Tensor) -> None:
        self.x = x
        self.y = y

    def __len__(self) -> int:
        return len(self.x)

    def __getitem__(self, idx: int) -> tuple:
        return (self.x[idx], self.y[idx])

In [20]:
# demo data

x = torch.randn(200)
y = torch.randint(0, 2, (200,))

In [21]:
dataset = CustomeAgeDataset(x=x, y=y)

dataloader = DataLoader(dataset=dataset, batch_size=40, shuffle=True)

In [22]:
count = 0
for batch_x, batch_y in dataloader:
    print(f"Batch {count}")
    print(batch_x)
    print(batch_y)
    count += 1

Batch 0
tensor([ 0.5892,  0.1758, -0.3047,  0.3475, -0.2410,  0.8803, -0.3396, -0.1858,
        -0.5859,  0.6469,  0.2936,  0.3907, -0.1525,  0.7540,  0.4148,  0.3767,
         1.2483,  0.5344, -0.9504,  1.7786,  0.9964, -0.4244,  0.9861,  1.6197,
         0.7428, -1.0360,  1.6623, -1.4740,  1.6818, -2.1895,  0.6630,  0.5016,
         0.0804,  0.3926, -1.2677, -0.8104, -0.1332,  1.6173, -0.7722, -0.0493])
tensor([1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
        0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1])
Batch 1
tensor([ 0.2817, -1.6291,  0.8956, -0.6326,  0.3131, -0.2274,  1.7784,  0.3303,
        -1.1324,  1.7283, -1.0814,  1.0537,  0.5527,  1.9825, -0.7289,  0.1293,
        -1.7659,  0.4626,  0.2874,  0.9505,  0.2121,  0.4342,  0.0114, -0.5615,
        -0.5516,  0.0781, -1.0935,  0.4623, -0.6161, -0.4817, -1.8763, -1.2786,
         0.4124,  0.5139,  1.5719, -1.6545, -0.4826, -0.2498,  0.7355,  0.3633])
tensor([0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1

- while traninig deep learning model, we using batched training.
- this comes under the epoch loop,

**In Simply**
- 1 epoch means the model traverse on entire dataset,
- Batch means split out dataset into chunks. 1 epoch complte the model go through all batches

### **Save Model Parameters, Checkpoint**

In [2]:
# just create a dummy FNN model

model = torch.nn.Sequential(
    torch.nn.Linear(2, 20),
    torch.nn.ReLU(),
    torch.nn.Linear(20, 1)
)

In [ ]:
# AND gate data
x = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]]).float()
y = torch.tensor([0, 0, 0, 1])

In [52]:
criterion = torch.nn.BCEWithLogitsLoss()
optim = torch.optim.Adam(model.parameters(), lr=0.001)

In [56]:
model.train()
for i in range(201):
    logits = model(x)
    loss = criterion(logits, y.reshape(-1, 1).float())
    optim.zero_grad()
    loss.backward()
    optim.step()

    if i % 20 == 0:
        print(f"Epoch: {i}, Loss: {loss.item()}")

Epoch: 0, Loss: 0.5704057216644287
Epoch: 20, Loss: 0.5459808707237244
Epoch: 40, Loss: 0.5219535827636719
Epoch: 60, Loss: 0.49821385741233826
Epoch: 80, Loss: 0.47437456250190735
Epoch: 100, Loss: 0.45078474283218384
Epoch: 120, Loss: 0.42768943309783936
Epoch: 140, Loss: 0.4048890471458435
Epoch: 160, Loss: 0.38244926929473877
Epoch: 180, Loss: 0.36050403118133545
Epoch: 200, Loss: 0.3391232192516327


In [58]:
torch.save(model.state_dict(), "./hello.pt")