<a href="https://colab.research.google.com/github/adnaen/machine-learning-notes/blob/main/deep_learning/0_pytorch/start_with_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PyTorch Tutorial To Get Started**

In [1]:
import torch

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

**Tensors**
```
scaler = single value
vector = 1-Dim tensor
matrix = 2-Dim tensor
tensor = N-Dim tensor
```

create random (3,4) `tensor` and print its shape

In [3]:
random_tensor = torch.rand((3,4), device=device)
print(f"Random Tensor: {random_tensor}")
print(f"Tensor size: {random_tensor.shape}")
print(f"Tensor Dimension : {random_tensor.ndim}")

Random Tensor: tensor([[0.3000, 0.5918, 0.0205, 0.7790],
        [0.1688, 0.5744, 0.0118, 0.1903],
        [0.7728, 0.5215, 0.4036, 0.2715]], device='cuda:0')
Tensor size: torch.Size([3, 4])
Tensor Dimension : 2


create tensor with `ones` with shape (2,5), and convert it to Numpy Array

In [4]:
ones_tensor = torch.ones((2,5), device=device)
ones_tensor.cpu().numpy()

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

perform `element wise addition` of two tensors of shape (4,4)

In [5]:
a = torch.rand(4,4, device=device)
b = torch.rand(4,4, device=device)
print(f"A : {a}")
print(f"B : {b}")

sum_of_ab = a + b
mul_of_ab = a * b

print(f"Sum of A and B : {sum_of_ab}")
print(f"Multiply A with B : {mul_of_ab}")

A : tensor([[0.5581, 0.5252, 0.1874, 0.8302],
        [0.5858, 0.0533, 0.2477, 0.8960],
        [0.1217, 0.6605, 0.0983, 0.2517],
        [0.8763, 0.4282, 0.5374, 0.9206]], device='cuda:0')
B : tensor([[0.1514, 0.2348, 0.8407, 0.2157],
        [0.0991, 0.1579, 0.9596, 0.9518],
        [0.8605, 0.8671, 0.3850, 0.1871],
        [0.6113, 0.5119, 0.0688, 0.3901]], device='cuda:0')
Sum of A and B : tensor([[0.7095, 0.7601, 1.0281, 1.0460],
        [0.6849, 0.2112, 1.2074, 1.8477],
        [0.9823, 1.5276, 0.4833, 0.4388],
        [1.4876, 0.9401, 0.6062, 1.3106]], device='cuda:0')
Multiply A with B : tensor([[0.0845, 0.1234, 0.1576, 0.1791],
        [0.0580, 0.0084, 0.2377, 0.8528],
        [0.1047, 0.5727, 0.0378, 0.0471],
        [0.5357, 0.2192, 0.0370, 0.3591]], device='cuda:0')


create a tensor with values [2,6,8] and `reshape` it into a (2,2)

In [6]:
new_tensor = torch.tensor([2, 4, 6, 8])
new_tensor.reshape([-1,2])

tensor([[2, 4],
        [6, 8]])

`generate a tensor` of random integers between 0 and 10 wih shape (3,3)

In [7]:
torch.randint(low=0, high=10, size=(3,3), device=device)

tensor([[2, 3, 8],
        [7, 6, 9],
        [5, 0, 6]], device='cuda:0')

### **AutoGrad**
- autograd automatically computes gradients for tensors involved in computation.
- It tracks all operations on tensors that have requires_grad=True and builds a computational graph dynamically.
- This enables backpropagation, where gradients are computed and stored for optimization.

In [8]:
# define a autograd enabled tensor
x = torch.tensor(2., requires_grad=True)
y = torch.tensor(5., requires_grad=True)

print(f"x : {x}")
print(f"y : {y}")

x : 2.0
y : 5.0


In [9]:
result = x**2 + y**2
print(f"Result : {result}")

Result : 29.0


In [10]:
# backpropgation
result.backward()

In [11]:
#find gradient
x.grad

tensor(4.)

In [12]:
y.grad

tensor(10.)

In [13]:
# reset a autograd
x.grad.zero_()

tensor(0.)

In [14]:
y.grad.zero_()

tensor(0.)

In [15]:
# run without autograd for temporary
with torch.no_grad():
    y = x*2 # not tracked

In [16]:
# detach autograd
z = y.detach()

In [17]:
# check if a tensor enabled autograd by
print(y.requires_grad)
print(x.requires_grad)

False
True


## **Dataset, DataLoader, Batch Traning**

- Implement Abstract Dataset class, with `__len__`, `__getitem__` methods.

In [18]:
from torch.utils.data import Dataset, DataLoader

In [26]:
class CustomeAgeDataset(Dataset):
    def __init__(self, x: torch.Tensor, y: torch.Tensor) -> None:
        self.x = x
        self.y = y

    def __len__(self) -> int:
        return len(self.x)

    def __getitem__(self, idx: int) -> tuple:
        return (self.x[idx], self.y[idx])

In [27]:
# demo data

x = torch.randn(200)
y = torch.randint(0, 2, (200,))

In [28]:
dataset = CustomeAgeDataset(x=x, y=y)

dataloader = DataLoader(dataset=dataset, batch_size=40, shuffle=True)

In [30]:
count = 0
for batch_x, batch_y in dataloader:
    print(f"Batch {count}")
    print(batch_x)
    print(batch_y)
    count += 1

Batch 0
tensor([ 0.2421,  0.7291, -0.3071, -1.4032,  0.1107, -0.3651,  0.4047, -2.7415,
        -0.2617, -1.1617,  0.3925,  2.0454, -1.9182,  2.1906,  0.5570,  0.1330,
         0.5722, -0.4240,  1.0280, -0.8951,  1.0037, -0.5076, -1.8809, -1.4003,
         0.2853,  0.7065,  0.3381,  1.6517,  0.1253, -0.7566, -2.0574, -0.0351,
        -0.3854, -0.2733, -1.5034,  0.0376,  0.0476,  0.3671,  1.2494, -1.4056])
tensor([1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0])
Batch 1
tensor([-0.0266, -0.4916,  1.3733,  0.6968,  0.5315, -0.9435,  0.1442,  0.1362,
        -1.0816,  1.7042, -0.7331,  1.0579, -0.3523,  0.6335, -2.1486,  0.0970,
         0.8896, -1.5390,  1.1429,  0.3563, -0.7235, -1.9708, -1.0839, -1.2190,
         0.5290, -1.2448,  0.2023,  0.9467,  0.5589,  1.1294, -0.2354,  0.0043,
         0.6745, -0.6112, -1.4758, -0.9249, -0.7548,  1.9881, -1.7153,  1.0958])
tensor([0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1

- while traninig deep learning model, we using batched training.
- this comes under the epoch loop,

**In Simply**
- 1 epoch means the model traverse on entire dataset,
- Batch means split out dataset into chunks. 1 epoch complte the model go through all batches